app/models.py
from flask_login import UserMixin
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    post = db.relationship("Post",backref = "user",lazy = "dynamic")
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    comment = db.relationship('Comment',backref = 'role',lazy="dynamic")



    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)




    def __repr__(self):
        return f'User {self.username}'



class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'



class Post(db.Model): 

    __tablename__ ='posts'

    id = db.Column(db.Integer, primary_key = True)
    post_title = db.Column(db.String)
    post_content = db.Column(db.Text)
    posted_at = db.Column(db.Date)
    post_by =db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship("Comment",backref ="post", lazy="dynamic")

    def save_post(self):
        db.session.add(self)
        db.session.commit()



    def delete_post(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def get_user_posts(cls,id):
        post = Post.query.filter_by(user_id= id).order_by(Post.posted_at.desc().all)
        return posts

    @classmethod
    def get_post(cls,id):
        return Post.query.filter_by(id)







class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    post_id =db.Column(db.Integer,db.ForeignKey('posts.id'))
    comment = db.Column(db.Text(),nullable = False)
    posted=db.Column(db.DateTime,default=datetime.utcnow)
    comment_by = db.Column(db.String)



    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def delete_comment(cls,id):
        gone =Comment.query.filter_by(id = id).first()
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def clear_comments(cls):
        commennts = Comment.query.filter_by(post_id =id).all()
        return comments


    @classmethod
    def get_comments(cls,id):
        commennts = Comment.query.filter_by(post_id =id).all()
        return comments
    

    
class Quote:
    """
    Quote class to define quote objects
    """

    def __init__(self,author,id,quote,permalink):
        self.author = author
        self.id = id
        self.quote = quote
        self.permalink = permalink

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    comment = TextAreaField('Post Comment', validators=[Required()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):

    title = StringField('Post Title',validators=[Required()])
    blogpost = TextAreaField('Post Content', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

# Initializing application

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)


app = Flask(__name__)

def create_app(config_name):
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..requests import get_quotes
from ..models import Comment,User,Post
from .forms import CommentForm,UpdateProfile,PostForm
from flask_login import login_required,current_user
import datetime
from .. import db,photos
import requests


# Views
@main.route('/')
def index():
    posts = Post.query.all()
    

    title = 'E-BLOG | Home'
    quotes = requests.get("http://quotes.stormconsultancy.co.uk/random.json").json()
    # random_quotes = get_quotes
    return render_template('index.html', title=title,posts=posts, quotes = quotes)

@main.route('/new_post/', methods = ['GET','POST'])
@login_required
def new_post():

    post_form = PostForm()
    if post_form.validate_on_submit():
        post_title = post_form.title.data
        post_content = post_form.blogpost.data

        new_post = Post(post_title = post_title,post_content = post_content, user_id = current_user.id)
        new_post.save_post()
        return redirect(url_for('main.index'))

    return render_template('new_post.html',post_form=post_form)

@main.route('/post/<int:id>', methods = ['GET','POST'])
def single_post(id):
    post = Post.query.filter_by(id=id).first()
    comments = Comment.query.filter_by(post_id=id).all()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data
        form.comment.data =''

        new_comment = Comment(comment=comment,post_id=post.id,user_id=current_user.id,comment_by=current_user.username)

        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('main.single_post', id = post.id))


    return render_template('single_post.html', post=post, comments=comments, form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/post/<int:id>/delete', methods = ['POST'])
@login_required
def delete_post(id):
    post = Post.query.filter_by(id = id).first()
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('main.index'))

app/templates/base.html
{% block style%}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
{% endblock %}
{% extends 'bootstrap/base.html'%}
<!-- Navbar block   -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> E-BLOG - Welcome to my online Space. </title>
    {% endif %}
</head>

<body>
    {% block content %}
    <div class="container-fluid text-center"
        style="background-image: url(https://scx2.b-cdn.net/gfx/news/hires/2018/4-ocean.jpg); height: 480px; background-repeat:no-repeat; background-position: top; background-size: cover; background-attachment: fixed; background-position: center; margin-bottom: 4%; ">
        <div class="text-white text-center rgba-stylish-strong py-5 px-4">
            <div class="py-5">
                <h2 class="h2 text-white animated heartBeat"
                    style="font-family: 'Abril Fatface', cursive; font-size: 40px; margin-top: 7.5%; text-shadow: 1px 1px 4px#000;">
                    <i class="E-BLOG fa-newspaper"></i>
                    E-BLOG</h2>
                <div class="text-center quote">
                        <h4>{{ quotes["author"] }}</h4>
                        <p style="font-size: 30px; color: rgb(7, 22, 22);"><em>
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                            {{quotes["quote"]}}
                            <i class="fa fa-quote-right" aria-hidden="true"></i>
                        </em></p>

                </div>

            </div>
        </div>
    </div>


    <div class="container all-posts">
        
        {%for post in posts%}
        <div class="card">
            <h1><strong></strong><a href="{{url_for('main.single_post', id = post.id)}}"" class="
                blog_title" >{{post.post_title}}</a></strong></h1>
            <h3 class="blog_content">{{post.post_content | truncate (200) | safe}}</h3>
            <hr>


        </div>
        {%endfor%}
        <div class="text-center">
                <a class="btn btn-outline-success newpost" href="/new_post/"> Write New Blog Post</a>
        </div>
    </div>



    {% endblock%}

</body>

</html>

app/templates/navbar.html
<nav class="navbar sticky-top " style="background: rgb(10, 81, 90); font-size: 20px;">
    <div class="container navbr">
           
            <a class="nav-link" href="{{url_for('main.index')}}" style="position: left;"><i class="fa fa-home" aria-hidden="true"></i>&nbsp; Home</a>
            

        <ul class="nav navbar-nav navbar-right">
            
            {% if current_user.is_authenticated %}
            <li><a  href="{{url_for('main.profile',uname=current_user.username)}}"><i class="far fa-user"></i>&nbsp; My account</a></li>
            <li><a href="{{url_for('auth.logout')}}" class="lgn"><i class="fas fa-sign-out-alt"></i>&nbsp; Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}" class="lgn"><i class="fas fa-sign-in-alt"></i>&nbsp; Sign in</a></li>
            {%endif%}
        </ul>


    </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">

            
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(comment_form) }}
        </div>

    </div>

{% endblock %}

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

   

    <div class="col-md-4">

        {{ wtf.quick_form(post_form) }}
    </div>

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-7">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-5">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
            <div class="col-md-4">
                    
                        {% if user == current_user %}
                    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                
                      <input type="file"  name="photo" class="form-control" required>
                      <input type="submit">
                    </form>
                      {% endif %}
                  
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/single_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
                <h1 class="blog_title"><strong>{{post.post_title}}</strong></h1>
            <div>
                <button type="button" class="btn-danger btn-sm m-1" data-toggle="modal"
                    data-target="#deleteModal">Delete</button>
            </div>
            <hr>
            <h3 class="blog_content">{{post.post_content}}</h3>

        </div>      
    </div>
    <div class="container">
            <div class="col-md-8">
                {% if comments %}
                {%for comment in comments%}
                <ul>
                    <li>{{comment.comment}}</li>
                </ul>
                {%endfor%}

                {% endif %}
            </div>
    
            <div class="col-md-4">
    
                {{ wtf.quick_form(form) }}
            </div>
    
        </div>

</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are You Sure?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('main.delete_post', id = post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}